name: Build dttStaging APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: ./gradlew assembleDttStagingRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dttStaging-apk
          path: app/build/outputs/apk/dttStaging/release/app-dttStaging-release.apk
